### ISSUE TITLE
if you were to quit data science, what would you do

### ISSUE THREAD

**Issue by imdyangs** [jxnl/ama#13]
other than retire

**Comment by jxnl** [comment]
I'd love to get back into design. Be a art director, maybe an architect. I really want to study industrial design too.

**Comment by jxnl** [comment]
I could also consider PhD and be a lecturer. I'm really passionate about the things I enjoy and I've always liked knowing that I can help people grow and develop themselves. So being able to inspire the younger generation is something that would probably give my life lots of meaning
