### ISSUE TITLE
What was the process like getting the research opportunity with a prof in NYU?

### ISSUE THREAD

**Issue by mohanwu** [jxnl/ama#14]
Did you reach out to a lot of professors and what did they look for?

**Comment by jxnl** [comment]
I got the opportunity through Waterloo Works (job mine at the time).

The interview was pretty much about the work I did my previous interviews. On top of that, my supervisors research was mostly about social media and my internship was about that topic so I had an advantage.

Living in NY was amazing, and I think the experience of being independent is pretty awesome. I usually worked from home and met with my supervisor every few weeks. My coop was 4 months long, but I ended up working on the paper for about a year and a bit. 

Going to conferences to present your work was also a great feeling and meeting people and listening to state of the art is also really exciting.

**Comment by jxnl** [comment]
Also, so much talent leaves academia, o think often times profs just want enthusiastic students with energy to get the work done.
