### ISSUE TITLE
What are your thoughts about graduate school? 

### ISSUE THREAD

**Issue by anornotan** [jxnl/ama#15]

**Comment by jxnl** [comment]
Yeah totally, its still an open door. 

Honestly the only reasons right now is that my employer (Stitchfix) is so full of PhDs and talented researchers that I think going to work first is better for building a stronger foundation in applied machine learning. 

The research I want to do is in Social Computing and I think I've been given a platform to do my research. 

We also can't forget the fact that being paid much more while doing the research I want is worth more than doing the research I want and not getting paid, in hopes of getting a paper that convince people to pay me.
