### ISSUE TITLE
Best way to start out in DS?

### ISSUE THREAD

**Issue by ghost** [jxnl/ama#2]
What do you think is the best way to get started in order to get in to this field?
What would you say are the essentials everyone needs in this field?

**Comment by jxnl** [comment]
I'll open with two posts that are kinda related and I'll have more detail as subsequent comments.

[quora: data science 1 - how to study](https://www.quora.com/Jason-Liu-How-do-you-know-so-much-about-data-science-and-machine-learning-How-do-you-study)

[quora: data science 2 - getting started](https://www.quora.com/I-see-lots-of-people-asking-how-to-become-a-data-scientist-but-what-is-a-realistic-timeframe-for-getting-a-full-time-job-starting-from-ground-zero/answer/Jason-Liu-21?)

**Comment by jxnl** [comment]
# Tools

In terms of tools i suggest learning R and Python. Not one or the other, but really both.

Pick up tools like Pandas and Dplyr, seaborn and ggplot2. That should get you started just being able  to manipulate and visualize data. 

* recommending viewing - [Pandas](https://www.youtube.com/watch?v=5JnMutdy6Fw)
* recommended reading - [Data Science in R](http://r4ds.had.co.nz)

## Seriously read  [Data Science in R](http://r4ds.had.co.nz) at least.

While I don't think Kaggle competitions is a good place to learn data science, i believe the kernels are a great place to learn about code.

* recommending browsing - [Kaggle Kernels](https://www.kaggle.com/kernels)

**Comment by jxnl** [comment]
# Intro Mathematics 

First I'd recommend [Andrew Ng's Coursera Course on Machine Learning](https://www.coursera.org/learn/machine-learning).

## Book Recommendation
**If I was to recommend one book it would be this it will take you from start to finish.**

[Elements of Statistical Learning](http://www.goodreads.com/book/show/148009.The_Elements_of_Statistical_Learning)

![](http://images.gr-assets.com/books/1387738132l/148009.jpg)

**Comment by jxnl** [comment]
# Online Sources

I'd suggest using [DataTau](www.datatau.com) to find interesting articles and also find bloggers that you like to read.

**Comment by jxnl** [comment]
## Secondary Book Recommendations

Facebook Analytics suggested these books so I'll pass them along too.
*  [Edward Tufte Visual Display of Quantitative Information.](http://www.amazon.com/The-Visual-Display-Quantitative-Information/dp/0961392142)

* [How to lie with statistics.](http://www.amazon.com/How-Lie-Statistics-Darrell-Huff/dp/0393310728/ref=sr_1_1?s=books&ie=UTF8&qid=1415817828&sr=1-1&keywords=how+to+lie+with+statistics)

* [Say it with Charts.](http://www.amazon.com/Say-Charts-Executives-Visual-Communication/dp/007136997X/ref=sr_1_1?s=books&ie=UTF8&qid=1415817867&sr=1-1&keywords=say+it+with+charts)

* [Beautiful Data.  Ok, has good stories in it, edited by a former FB'er.](http://www.amazon.com/Beautiful-Data-Stories-Elegant-Solutions/dp/0596157118/ref=sr_1_1?s=books&ie=UTF8&qid=1415817995&sr=1-1&keywords=beautiful+data)

* [Nate Silver's book](http://www.amazon.com/Signal-Noise-Many-Predictions-Fail/dp/159420411X)
* [Daniel Kahneman's book](http://www.amazon.com/Thinking-Fast-Slow-Daniel-Kahneman/dp/0374533555)

**Comment by srcreigh** [comment]
FYI "elements of statistical learning" is available online via UW library

http://www.lib.uwaterloo.ca/find.php?sstring=elements+of+statistical+learning

**Comment by srcreigh** [comment]
actually here's a direct link. just click "read this book", then click university of waterloo, then log in.

http://books2.scholarsportal.info/viewdoc.html?id=/ebooks/ebooks0/springer/2010-02-11/1/9780387848587
