### ISSUE TITLE
What is your favourite city to work in?

### ISSUE THREAD

**Issue by w268wang** [jxnl/ama#4]

**Comment by jxnl** [comment]
Between San Francisco and New  York, which are my two main coops, my favourite city is New York, but I think financially San Francisco is better. 

I prefer cities where i can walk to work and do most things. My issue with SF as a walking city is all the homelessness which is, not ideal.

I ended up turning down south bay work and moved to downtown san Francisco, and its way better having friends walking distance from work and being able to leave anytime and not worry about trains.

**Comment by jxnl** [comment]
I think the thing that sucks about the bay is that could live all across the bay and the trains suck.

**Comment by jxnl** [comment]
While I expect to be living in Menlo Park at Facebook, I expect that I'll be visiting New York often.

**Comment by jxnl** [comment]
Answer is still NYC but I'll be working in SF for the time being
