### ISSUE TITLE
Could you list some of the data science problems you worked on in the past?

### ISSUE THREAD

**Issue by herougo** [jxnl/ama#5]
I'm curious about the problem-solving process you go through when investigating a data science problem; that is, how you applied the algorithms and gained insight from the data. Could you list some specific data science problems are briefly explain how you  visualized the data and tweaked your model to improve performance? You could also include major obstacles and how you overcame them. Thanks.

**Comment by jxnl** [comment]
1. Understanding fashion using machine learning
2. Multi-Bandit problems for ad optimization
3. two-sigma rental listing challenge
4. consulting for companies (email marking campaigns)
5. analyzing tweets to learn about population alcohol consumption 
6. using autoencoders to learn image hashs.

feel free to ask about specific ones in detail.

**Comment by herougo** [comment]
Could you talk about 3 and 5? Thanks.

**Comment by jxnl** [comment]
@herougo I'll actually be writing about those two so stay tuned.
Both will end up as papers.

**Comment by jxnl** [comment]
@herougo http://dl.acm.org/citation.cfm?id=2998336&CFID=749057000&CFTOKEN=43714826 is the twitter one. the two-sigma one will be out by 25th
