### ISSUE TITLE
Useful stat courses at University of Waterloo

### ISSUE THREAD

**Issue by srcreigh** [jxnl/ama#7]
I want to get a handle on basic data analysis. Since I'm studying at UW, I decided that I might as well take 2-3 STAT courses to that end, as long as UW has the right courses.

I took a look at your [transcript](https://github.com/jxnl/ama/issues/3) and that [stat courses at UW](http://www.ucalendar.uwaterloo.ca/1718/COURSE/course-STAT.html) and decided that these two would be good:

- STAT 331
- STAT 341

You said that STAT 331 is useful, but STAT 341 is more theoretical (i.e. isn't used much for practical data analysis).

So my question is: **what useful STAT courses are there at Waterloo other than stat 341?**

**Comment by jxnl** [comment]
STAT 441: Classification (taught by Ali Ghodsi) is a great course
STAT 442: Visualization (taught by Ali Ghodsi) is also pretty good too.

I took STAT 331 with Martin Lysy who is a great prof and teaches a solid mathematical foundation. 

I recommend taking any course available that is taught Ali Ghodsi or Martin Lysy.

**Comment by jxnl** [comment]
I'd say read STAT 333 course notes too as the concepts are pretty useful. My friend @tcfraser has some great notes at http://tcfraser.com/coursenotes/
