### ISSUE TITLE
Advice: 0 to hero

### ISSUE THREAD

**Issue by RobertRiachi** [jxnl/ama#8]
Currently I am reading r4ds, elements of statistical learning, and miscellaneous papers. I was wondering if there should be any other dimension that I should add to my learning process in order to go from 0 to hero in data science and/or ML.

**Comment by jxnl** [comment]
recommendation:

find a project that you can do in a few  (3-5) days, write all the code and run stuff. Then wait a week, and write a post about it.

**Comment by RobertRiachi** [comment]
When you say project, would it be more of a programming oriented project or a stats based analysis? Could you give an example of one, not for me to use specifically, but just so that I can gather a general idea.

**Comment by jxnl** [comment]
Take a kaggle dataset and come up with an insight! 

I think the best way to get experience in a public setting is to post Kernels on Kaggle.
